# Generated by Django 5.1.7 on 2025-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='program',
            field=models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('M.Tech', 'Master of Technology'), ('BCA', 'Bachelor of Computer Applications'), ('MCA', 'Master of Computer Applications')], default='B.Tech', max_length=100),
        ),
    ]
