# Generated by Django 5.1.7 on 2025-09-18 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('email_college', models.EmailField(max_length=254, unique=True)),
                ('email_personal', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('permanent_address', models.TextField()),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bachelor_college', models.CharField(max_length=255)),
                ('bachelor_course', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electronics and Communication')], max_length=50)),
                ('bachelor_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('master_college', models.CharField(blank=True, max_length=255, null=True)),
                ('master_course', models.CharField(blank=True, choices=[('MCA', 'Master of Computer Applications'), ('MSIT', 'Master of Science in IT')], max_length=50, null=True)),
                ('master_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('active_backlogs', models.IntegerField(default=0)),
                ('batch_year', models.IntegerField()),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('resume_link', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PLACED', 'Placed'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20)),
                ('can_apply', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, to='students.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
