# Generated by Django 5.1.7 on 2025-09-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bachelor_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bachelor_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bachelor_course',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electronics and Communication'), ('BCA', 'Bachelor of Computer Applications'), ('BScIT', 'Bachelor of Science in IT'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='master_course',
            field=models.CharField(blank=True, choices=[('MCA', 'Master of Computer Applications'), ('MSIT', 'Master of Science in IT'), ('M.Tech', 'Master of Technology'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='10th Grade Percentage', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='12th Grade Percentage', max_digits=5, null=True),
        ),
    ]
