# Generated by Django 5.1.7 on 2025-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='eligibility_criteria',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='application_deadline',
            field=models.DateField(default='2025-07-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Full-Time', 'Full-Time'), ('Both', 'Both')], default='Internship', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_work_details',
            field=models.TextField(default='No details provided yet', help_text='Overview of what the company does'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='extra_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='foundation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='owner_details',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='package',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='pdf_link',
            field=models.URLField(blank=True, help_text='Google Drive PDF link'),
        ),
        migrations.AddField(
            model_name='company',
            name='position_details',
            field=models.TextField(default='No details provided yet', help_text='Details about roles or positions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='required_skills',
            field=models.TextField(default='No details provided yet', help_text='Comma-separated skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='stipend',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
