# Generated by Django 5.1.7 on 2025-06-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_remove_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
