# Generated by Django 5.1.7 on 2025-09-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('hr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hr_email', models.EmailField(max_length=254)),
                ('hr_contact', models.CharField(max_length=15)),
                ('secondary_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('technical_description', models.TextField(blank=True, null=True)),
                ('other_description', models.TextField(blank=True, null=True)),
                ('preferred_courses', models.CharField(blank=True, max_length=255, null=True)),
                ('hiring_types', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('FULLTIME', 'Full-time'), ('BOTH', 'Both')], default='FULLTIME', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EligibleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('FULLTIME', 'Full-time'), ('BOTH', 'Both')], default='FULLTIME', max_length=50)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('batch_year', models.IntegerField()),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField()),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('pdf_details', models.FileField(blank=True, null=True, upload_to='job_pdfs/')),
                ('application_deadline', models.DateField()),
                ('drive_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('eligible_courses', models.ManyToManyField(to='companies.eligiblecourse')),
            ],
        ),
    ]
